"""LSD input file generator from NMR peak data."""

from pathlib import Path

from lucy_ng.lsd.models import Hybridization, LSDAtom, LSDCorrelation, LSDProblem
from lucy_ng.models import PeakList1D, PeakList2D
from lucy_ng.processing.dept_guided_picker import DEPTGuidedResult


class LSDInputGenerator:
    """Generate LSD input files from NMR peak data.

    Converts peak lists from NMR experiments into LSD format:
    - 13C peaks → atom definitions (MULT)
    - HSQC peaks → direct C-H correlations
    - HMBC peaks → long-range C-H correlations
    - COSY peaks → H-H correlations
    """

    @staticmethod
    def generate(problem: LSDProblem) -> str:
        """Generate LSD input file content from problem definition.

        Args:
            problem: Complete LSD problem with atoms and correlations

        Returns:
            String content of LSD input file
        """
        lines = []

        # Header comments
        lines.append(f"; LSD input file: {problem.name}")
        lines.append("; Generated by lucy-ng")
        if problem.molecular_formula:
            lines.append(f"; Molecular formula: {problem.molecular_formula}")
        for comment in problem.comments:
            lines.append(f"; {comment}")
        lines.append("")

        # Atom definitions (MULT commands)
        if problem.atoms:
            lines.append("; Atom definitions")
            for atom in sorted(problem.atoms, key=lambda a: a.index):
                lines.append(atom.to_mult_line())
            lines.append("")

        # Chemical shifts (SHIX for 13C, SHIH for 1H)
        shifts_added = False
        for atom in sorted(problem.atoms, key=lambda a: a.index):
            if atom.carbon_shift is not None:
                if not shifts_added:
                    lines.append("; Chemical shifts")
                    shifts_added = True
                lines.append(f"SHIX {atom.index} {atom.carbon_shift:.2f}")
        if shifts_added:
            lines.append("")

        # Group correlations by type
        hsqc_corrs = [c for c in problem.correlations if c.correlation_type in ("HSQC", "HMQC")]
        hmbc_corrs = [c for c in problem.correlations if c.correlation_type == "HMBC"]
        cosy_corrs = [c for c in problem.correlations if c.correlation_type == "COSY"]

        # HSQC correlations
        if hsqc_corrs:
            lines.append("; Direct C-H correlations (HSQC)")
            for corr in hsqc_corrs:
                lines.append(corr.to_lsd_line())
            lines.append("")

        # HMBC correlations
        if hmbc_corrs:
            lines.append("; Long-range C-H correlations (HMBC)")
            for corr in hmbc_corrs:
                lines.append(corr.to_lsd_line())
            lines.append("")

        # COSY correlations
        if cosy_corrs:
            lines.append("; H-H correlations (COSY)")
            for corr in cosy_corrs:
                lines.append(corr.to_lsd_line())
            lines.append("")

        # End marker
        lines.append("EXIT")

        return "\n".join(lines)

    @staticmethod
    def write_file(problem: LSDProblem, output_path: Path | str) -> Path:
        """Write LSD input file to disk.

        Args:
            problem: LSD problem to write
            output_path: Path for output file

        Returns:
            Path to written file
        """
        output_path = Path(output_path)
        content = LSDInputGenerator.generate(problem)
        output_path.write_text(content)
        return output_path

    @staticmethod
    def from_peak_data(
        carbon_peaks: PeakList1D,
        hsqc_peaks: PeakList2D | None = None,
        hmbc_peaks: PeakList2D | None = None,
        cosy_peaks: PeakList2D | None = None,
        dept_result: DEPTGuidedResult | None = None,
        molecular_formula: str | None = None,
        name: str = "problem",
        tolerance: float = 1.0,
    ) -> LSDProblem:
        """Build LSD problem from NMR peak data.

        Creates atom definitions from 13C peaks and correlations from 2D spectra.

        Args:
            carbon_peaks: 1D 13C peak list (defines atoms)
            hsqc_peaks: HSQC 2D peak list (optional)
            hmbc_peaks: HMBC 2D peak list (optional)
            cosy_peaks: COSY 2D peak list (optional)
            dept_result: DEPT-guided result for multiplicity info (optional)
            molecular_formula: Molecular formula string (optional)
            name: Problem name
            tolerance: ppm tolerance for peak matching

        Returns:
            LSDProblem ready for input file generation
        """
        problem = LSDProblem(
            molecular_formula=molecular_formula,
            name=name,
        )

        # Build atom index mapping: carbon ppm → atom index
        # Sort by ppm descending (high field first, as is NMR convention)
        sorted_carbons = sorted(carbon_peaks.peaks, key=lambda p: -p.position)
        ppm_to_index: dict[float, int] = {}

        for i, peak in enumerate(sorted_carbons, start=1):
            ppm_to_index[peak.position] = i

            # Determine hybridization and H count from DEPT if available
            hybridization = Hybridization.SP3  # Default
            hydrogen_count = 0  # Default (quaternary)

            if dept_result and dept_result.carbon_multiplicities:
                # Find matching DEPT carbon
                for dept_ppm, mult in dept_result.carbon_multiplicities.items():
                    if abs(dept_ppm - peak.position) <= tolerance:
                        if mult == "CH2":
                            hydrogen_count = 2
                            hybridization = Hybridization.SP3
                        elif mult == "CH":
                            hydrogen_count = 1
                            # Could be sp2 or sp3, default to sp3
                            hybridization = Hybridization.SP3
                        elif mult == "CH3":
                            hydrogen_count = 3
                            hybridization = Hybridization.SP3
                        elif mult == "CH/CH3":
                            # Ambiguous, assume CH (1 H) for now
                            hydrogen_count = 1
                            hybridization = Hybridization.SP3
                        break

            atom = LSDAtom(
                index=i,
                element="C",  # Only carbons for now
                hybridization=hybridization,
                hydrogen_count=hydrogen_count,
                carbon_shift=peak.position,
            )
            problem.add_atom(atom)

        # Helper to find atom index for a ppm value
        def find_atom_index(ppm: float) -> int | None:
            for carbon_ppm, idx in ppm_to_index.items():
                if abs(carbon_ppm - ppm) <= tolerance:
                    return idx
            return None

        # Add HSQC correlations
        if hsqc_peaks:
            seen_hsqc: set[tuple[int, int]] = set()
            for peak in hsqc_peaks.peaks:
                atom_idx = find_atom_index(peak.f1_position)
                if atom_idx is not None:
                    # H index same as C index for direct correlation
                    key = (atom_idx, atom_idx)
                    if key not in seen_hsqc:
                        seen_hsqc.add(key)
                        problem.add_correlation(LSDCorrelation(
                            atom1_index=atom_idx,
                            atom2_index=atom_idx,
                            correlation_type="HSQC",
                        ))

        # Add HMBC correlations
        if hmbc_peaks:
            seen_hmbc: set[tuple[int, int]] = set()
            for peak in hmbc_peaks.peaks:
                # F1 is carbon, F2 is proton
                carbon_idx = find_atom_index(peak.f1_position)
                if carbon_idx is not None:
                    # For HMBC, we need to find which H position correlates
                    # The H position relates to another carbon's attached H
                    # For now, use carbon index as H reference
                    # In reality, would need proton assignment

                    # Find which carbon the proton belongs to (from HSQC)
                    h_carbon_idx = None
                    if hsqc_peaks:
                        for hsqc in hsqc_peaks.peaks:
                            if abs(hsqc.f2_position - peak.f2_position) <= 0.1:  # Proton tolerance
                                h_carbon_idx = find_atom_index(hsqc.f1_position)
                                break

                    if h_carbon_idx is not None and h_carbon_idx != carbon_idx:
                        key = (carbon_idx, h_carbon_idx)
                        if key not in seen_hmbc:
                            seen_hmbc.add(key)
                            problem.add_correlation(LSDCorrelation(
                                atom1_index=carbon_idx,
                                atom2_index=h_carbon_idx,
                                correlation_type="HMBC",
                                min_bonds=2,
                                max_bonds=3,
                            ))

        # Add COSY correlations
        if cosy_peaks:
            seen_cosy: set[tuple[int, int]] = set()
            for peak in cosy_peaks.peaks:
                # Both F1 and F2 are protons - need to map to carbons via HSQC
                if hsqc_peaks:
                    h1_carbon = None
                    h2_carbon = None

                    for hsqc in hsqc_peaks.peaks:
                        if abs(hsqc.f2_position - peak.f1_position) <= 0.1:
                            h1_carbon = find_atom_index(hsqc.f1_position)
                        if abs(hsqc.f2_position - peak.f2_position) <= 0.1:
                            h2_carbon = find_atom_index(hsqc.f1_position)

                    if h1_carbon and h2_carbon and h1_carbon != h2_carbon:
                        key = tuple(sorted([h1_carbon, h2_carbon]))
                        if key not in seen_cosy:
                            seen_cosy.add(key)
                            problem.add_correlation(LSDCorrelation(
                                atom1_index=key[0],
                                atom2_index=key[1],
                                correlation_type="COSY",
                            ))

        return problem

    @staticmethod
    def from_dept_result(
        dept_result: DEPTGuidedResult,
        hmbc_peaks: PeakList2D | None = None,
        cosy_peaks: PeakList2D | None = None,
        molecular_formula: str | None = None,
        name: str = "problem",
        tolerance: float = 1.0,
    ) -> LSDProblem:
        """Build LSD problem from DEPT-guided result.

        Convenience method that uses DEPT result as primary source.

        Args:
            dept_result: Result from DEPTGuidedPicker
            hmbc_peaks: HMBC 2D peak list (optional)
            cosy_peaks: COSY 2D peak list (optional)
            molecular_formula: Molecular formula string
            name: Problem name
            tolerance: ppm tolerance for matching

        Returns:
            LSDProblem ready for input file generation
        """
        return LSDInputGenerator.from_peak_data(
            carbon_peaks=dept_result.dept_peaks,
            hsqc_peaks=dept_result.peaks,
            hmbc_peaks=hmbc_peaks,
            cosy_peaks=cosy_peaks,
            dept_result=dept_result,
            molecular_formula=molecular_formula,
            name=name,
            tolerance=tolerance,
        )
